version: '3.9'

services:
  db:
    container_name: food_delivery_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: food-delivery
    ports:
      - '5432:5432'
